spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      master:
        #        url: jdbc:mysql://localhost:3306/tests?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT
        url: jdbc:mysql://47.102.104.124:3306/tickets?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true&useAffectedRows=true&serverTimezone=Asia/Shanghai
        username: root
        password: root
      slave:
        enabled: false
        url:
        username:
        password:
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
        log4j:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
  # RabbitMQ配置信息
  rabbitmq:
    host: 47.102.104.124
    port: 5672
    username: admin
    password: admin
    virtual-host: my_tickets
#    connection-timeout: 10000
    listener:
      simple:
        acknowledge-mode: MANUAL # 自动应答 manual手动应答
        auto-startup: true
        default-requeue-rejected: false # 不重回队列
        concurrency: 5
        max-concurrency: 20
        prefetch: 1 # 每次只处理1个信息
        retry:
          enabled: true

#server:
#  max-http-header-size: 200MB
#  tomcat:
#    max-http-post-size: 200MB

server:
  max-http-header-size: 200MB
  tomcat:
    max-connections: 200 # Maximum number of connections that the server accepts and processes at any given time.
    max-http-post-size: 0 # Maximum size, in bytes, of the HTTP post content.
    max-threads: 300 # Maximum number of worker threads.
    min-spare-threads: 0 # Minimum number of worker threads.


# 忽略鉴权url
ignored:
  urls:
    - /dictData/getByType/**
    - /sys-user-po/regist
    - /common/**
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /test/**
    - /users/findByUserUame
    - /pm-goods-attribute-po/findByType/**
    - /v2/api-docs
    - /app/user/data/register
    - /app/user/data/reset
    - /app/user/data/binding
    - /generator/create
    - /app/order/logistics/callback/**

# 配置文件加密key
jasypt:
  encryptor:
    password: 123456

distribution:
  # 全局限流
  rateLimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  # token交互方式
  token:
    # 默认redis 设置为true后，token将存入redis，并具有单点登录功能 设为false将使用JWT交互
    redis: true
    # token中存储用户权限数据 设为true开启后可避免每次请求再获取用户权限，但有可能导致编辑权限菜单后无法读取到最新权限数据（需用户重新登录）
    storePerms: true
  # token过期时间（分钟）
  tokenExpireTime: 6000
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: false
  # 七牛云配置
  qiniu:
    accessKey: wkxcEQGakg0zhC4wxV_3dOxw42X2gQvkFuRq-lJr
    secretKey: 1Zbi1Tak2fHhJuwQqyLJfAiZHYI1iFQptTLAVr0-
    bucket: bohui_20190614
    domain: http://bo2h.com
    # 存储区域 -1自动判断 0华东 1华北 2华南 3北美 4东南亚
    zone: -1


# 微信小程序配置
wetch:
  applet:
    APP_ID: wx9f0839375a30274e
    SECRET: 905f26893b74727ede31a42b5e55a5dd
